package main

import (
	"log"
	"os"

	// docs are generated by Swag CLI, you have to import them.
	// replace with your own docs folder, usually "github.com/username/reponame/docs"
	"github.com/natersland/b2b-e-commerce-api/configs"
	"github.com/natersland/b2b-e-commerce-api/configs/databases"
	_ "github.com/natersland/b2b-e-commerce-api/docs"
	"github.com/natersland/b2b-e-commerce-api/modules/servers"
)

func envPath() string {
	if len(os.Args) == 1 {
		return ".env"
	} else {
		return os.Args[1]
	}
}

func main() {
	config := configs.ServerConfig(envPath())

	db, err := databases.InitDB(config.Db())
	if err != nil {
		log.Fatalf("Error initializing database: %v", err)
	}
	// Load configurations
	smtpcfg := configs.LoadConfig()
	servers.NewServer(config, smtpcfg, db).Start()
}
